#!/bin/sh
#
# Automates the process of getting the openembedded repo and then adding the
# TS7xxx branch on top of it.
#

set -e

if [ -d bitbake ]
then
	echo "BitBake directory already exists. Skipping download."
else
	echo "Fetching bitbake from svn..."
	svn co svn://svn.berlios.de/bitbake/branches/bitbake-1.8/ bitbake
fi

if [ -d openembedded ]
then
	echo "OpenEmbedded directory already exists. Cowardly exiting."
	exit 1
fi

#
# This sets origin to the official OE repository.
#
git clone git://git.openembedded.net/openembedded
cd openembedded

#
# This allows simple access to the oe-ts7xxx repository on top of the official
# OE repository.
#
git remote add github git://github.com/troth/oe-ts7xxx.git

#
# Now pull in the oe-ts7xxx stuff from github.
#
git pull github ts7800

echo
echo "If all went well, then you should tweak the SetupEnv script so that"
echo "BASE reflects where you installed oe-setup. Then you should be ready"
echo "to run the Make-console-image script"
echo
