#!/bin/sh
#
# Automates the process of getting the openembedded repo and then adding the
# TS7xxx branch on top of it.
#

TARGET="ts7390"

#
# Are we on the TARGET branch?
#
git checkout ${TARGET}

if [ -d bitbake ]
then
	echo "BitBake directory already exists. Skipping download."
else
	echo "Fetching bitbake from svn..."
	svn co svn://svn.berlios.de/bitbake/branches/bitbake-1.8/ bitbake
fi

if [ -d openembedded ]
then
	echo "OpenEmbedded directory already exists. That's good."
else
	echo "OpenEmbedded directory does not exist."
	echo "Cloning from git.openembedded.org..."
	git clone git://git.openembedded.org/openembedded
fi

#
# This sets origin to the official OE repository.
#
cd openembedded

#
# This creates a local branch for the ts7390
#
if git branch | grep ''${TARGET}'$'
then
	echo "${TARGET} branch exists"
else
	git branch --track ${TARGET} origin/org.openembedded.dev
	git checkout ${TARGET}
fi

#
# This allows simple access to the oe-ts7xxx repository on top of the official
# OE repository.
#
if ! grep '\[remote "github"\]' .git/config
then
	git remote add github git://github.com/troth/oe-ts7xxx.git
fi

#
# Now pull in the oe-ts7xxx stuff from github.
#
git pull github ${TARGET}

echo
echo "If all went well, then you should tweak the SetupEnv script so that"
echo "BASE reflects where you installed oe-setup. Then you should be ready"
echo "to run the ./Make-image script"
echo
