#!/bin/sh

export BB_ENV_EXTRAWHITE="OEBASE"

export OEBASE="${PWD}"

export BBPATH="${OEBASE}/build:${OEBASE}/openembedded"
export PATH="${OEBASE}/bitbake/bin:$PATH"

echo "OEBASE = ${OEBASE}"
echo "BBPATH = ${BBPATH}"
echo "PATH = ${PATH}"
