MOD_NAME = ts7800_keypad

MOD_SRC = \
	$(MOD_NAME)_main.c

DEBUG = y

include $(M)../Common.mk

#inst:
#	sudo cp $(MOD_NAME).ko /home/roth/dev/Linux/TS7800-root/test
#	sudo cp load_$(MOD_NAME) /home/roth/dev/Linux/TS7800-root/test
